<?xml version="1.0" ?>
<!-- Lamp -->
<robot name="lamp" xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- Lamp has 5 joints and 5 links -->

  <!--  Constants for robot dimensions -->
  <xacro:property name="height1" value="1" /> <!-- Link 1 -->
  <xacro:property name="height2" value="1" /> <!-- Link 2 -->
  <xacro:property name="height3" value="1" /> <!-- Link 3-->
  <xacro:property name="height4" value="1" /> <!-- Link 4 -->
  <xacro:property name="height5" value="1" /> <!-- Link 5-->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="gap_link" value="0.1" /> <!-- Distance gap between each axis --> 
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import Rviz colors -->
  <xacro:include filename="$(find lamp_description)/urdf/materials.xacro" />

<!-- ***************** WORLD ********************* -->
<!-- Used for fixing the robot to Gazebo 'base_link' -->
<link name="world"/>

<joint name="fixed" type="fixed">
  <parent link="world"/>
	<child link="link1"/>
</joint>

<!-- Base Link -->
<link name="link1">
  <collision>
    <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${width} ${width} ${height1}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${width} ${width} ${height1}"/>
    </geometry>
    <material name="orange"/>
  </visual>

  <inertial>
    <origin xyz="0 0 1" rpy="0 0 0"/>
    <mass value="1"/>
    <inertia
      ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
      iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
      izz="${mass / 12.0 * (width*width + width*width)}"/>
  </inertial>
</link>

<!-- ***************** JOINT1 ********************* -->
<!-- Used for fixing link1 to link2  -->
<joint name="joint1" type="continuous">
  <parent link="link1"/>
	<child link="link2"/>
  <origin xyz="0 ${gap_link} ${height1 - axel_offset}" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
  <dynamics damping="0.7"/>
</joint>

<link name="link2">
  <collision>
    <origin xyz="0 0 ${height2/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${width} ${width} ${height2}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 ${height2/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${width} ${width} ${height2}"/>
    </geometry>
    <material name="black"/>
 </visual>

  <inertial>
    <origin xyz="0 0 1" rpy="0 0 0"/>
    <mass value="1"/>
    <inertia
      ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
      iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
      izz="${mass / 12.0 * (width*width + width*width)}"/>
  </inertial>
</link>

<!-- ***************** JOINT2 ********************* -->
<!-- Used for fixing link2 to link3  -->
<joint name="joint2" type="continuous">
  <parent link="link2"/>
	<child link="link3"/>
  <origin xyz="0 ${gap_link} ${height2 - axel_offset}" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
  <dynamics damping="0.7"/>
</joint>

<link name="link3">
  <collision>
    <origin xyz="0 0 ${height3/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${width} ${width} ${height3}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 ${height3/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${width} ${width} ${height3}"/>
    </geometry>
    <material name="blue"/>
  </visual>

  <inertial>
    <origin xyz="0 0 1" rpy="0 0 0"/>
    <mass value="1"/>
    <inertia
      ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
      iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
      izz="${mass / 12.0 * (width*width + width*width)}"/>
  </inertial>
</link>

<!-- ***************** JOINT3 ********************* -->
<!-- Used for fixing link3 to link4  -->
<joint name="joint3" type="continuous">
  <parent link="link3"/>
	<child link="link4"/>
  <origin xyz="0 ${gap_link} ${height3 - axel_offset}" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
  <dynamics damping="0.7"/>
</joint>

<link name="link4">
  <collision>
    <origin xyz="0 0 ${height4/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${width} ${width} ${height4}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 ${height4/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${width} ${width} ${height4}"/>
    </geometry>
    <material name="red"/>
  </visual>

  <inertial>
    <origin xyz="0 0 1" rpy="0 0 0"/>
    <mass value="1"/>
    <inertia
      ixx="${mass / 12.0 * (width*width + height4*height4)}" ixy="0.0" ixz="0.0"
      iyy="${mass / 12.0 * (height4*height4 + width*width)}" iyz="0.0"
      izz="${mass / 12.0 * (width*width + width*width)}"/>
  </inertial>
</link>

<!-- ***************** JOINT4 ********************* -->
<!-- Used for fixing link4 to link5  -->
<joint name="joint4" type="continuous">
  <parent link="link4"/>
	<child link="link5"/>
  <origin xyz="0 ${gap_link} ${height4 - axel_offset}" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
  <dynamics damping="0.7"/>
</joint>

<link name="link5">
  <collision>
    <origin xyz="0 0 ${height5/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${width} ${width} ${height5}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 ${height5/2}" rpy="0 0 0"/>
    <geometry>
      <box size="${width} ${width} ${height5}"/>
    </geometry>
    <material name="green"/>
  </visual>

  <inertial>
    <origin xyz="0 0 1" rpy="0 0 0"/>
    <mass value="1"/>
    <inertia
      ixx="${mass / 12.0 * (width*width + height5*height5)}" ixy="0.0" ixz="0.0"
      iyy="${mass / 12.0 * (height5*height5 + width*width)}" iyz="0.0"
      izz="${mass / 12.0 * (width*width + width*width)}"/>
  </inertial>
</link>

</robot>

